### ISSUE TITLE
Appears to still be using python2

### ISSUE THREAD

**Issue by douglasawh** [stephensekula/navierstokes#12]
Python 2 is now EOL, but NS still seems to be using it (based on pip3 vs pip output, as well as trying to run it with python3 instead of python)

**Comment by douglasawh** [comment]
I see there is a dev branch for python3. Perhaps people should open issues on that branch so we can help get this out.

That said, I think most of my time will be spent in java-land for quite some time.

**Comment by stephensekula** [comment]
Old but not forgotten ... this issue is now resolved.
