### ISSUE TITLE
Mastodon support

### ISSUE THREAD

**Issue by nemobis** [stephensekula/navierstokes#8]
Nice tool, thanks. Sorry for the stupid question, but is Mastodon supported as GNUsocial type? I've set up my account https://quitter.se/wikimediaitalia and the script claims to have written to it, but no message has appeared.

**Comment by stephensekula** [comment]
I have never tried Mastodon and I'm not sure if we should expect it to just work. If Mastodon has implemented the same Twitter 1.X API that GNU Social has been using for years, then it ought to work and that then needs to be debugged. If their API is different, there are no guarantees. This will take me longer to track down. If you make any progress on this, let me know.

**Comment by nemobis** [comment]
Ok! I will try to check their specs, thanks for the responses.

**Comment by stephensekula** [comment]
Old but not forgotten ... this is now resolved.
